version: '3.2'
services:
  nginx:
    # 拉取镜像
    image: nginx
    restart: always
    volumes:
    # 挂载？目录文件以及权限 分别为项目目录 nginx配置 以及日志
      - ./app:/app:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./logs/nginx:/var/log/nginx:rw
    links:
    # 建立容器间链接
      - "php-fpm-71:php-fpm-71"
    ports:
      - "80:80"
  php-fpm-71:
    build: ./php/php-fpm-71/Dockerfile-dev
    restart: always
    links:
     - "mysql:mysql"
    volumes:
      - ./app:/app:rw
      - ./php/php-fpm-71/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
    # 数据同步
      - ./dates/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: zhabu
      MYSQL_PASSWORD: zbpwd
    # 这里其实还有数据库默认字符集设置  代码我忘记怎么写了
    # command:
    ports:
      - "3306:3306"
  mongodb:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
